services:
  chicken:
    image: nguyentienthanh2909/chicken
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chicken
    restart: always
    ports:
      - "3333:3000"
    env_file:
      - .env
    networks:
      - chicken_default

networks:
  chicken_default:
    external: true
